from app import app, db, SOUNDS_DIR
from uuid import uuid4
from yt_dlp import YoutubeDL
import os
from pathlib import Path
import time
import json

def get_cookies_path():
    """Get the path to the yt-dlp cookies file."""
    return Path.home() / ".config" / "yt-dlp" / "cookies.txt"

def is_youtube_authenticated():
    """Check if YouTube cookies are already saved."""
    return get_cookies_path().exists()

async def authenticate_youtube():
    """Authenticate with YouTube using Playwright browser automation.
    
    Opens a browser window for the user to log into YouTube,
    then saves the authentication cookies for yt-dlp to use.
    
    Returns: dict with 'success' and 'message' keys
    """
    try:
        from playwright.async_api import async_playwright
    except ImportError:
        return {
            'success': False,
            'message': 'Playwright not installed. Run: pip install playwright'
        }
    
    cookies_path = get_cookies_path()
    cookies_dir = cookies_path.parent
    cookies_dir.mkdir(parents=True, exist_ok=True)
    
    async with async_playwright() as p:
        # Launch browser in headed mode so user can see and interact
        browser = await p.chromium.launch(headless=False)
        context = await browser.new_context()
        page = await context.new_page()
        
        try:
            # Navigate to YouTube
            await page.goto('https://www.youtube.com')
            
            # Wait for user to log in (timeout after 5 minutes)
            await page.wait_for_url('**/youtube.com/**', timeout=5 * 60 * 1000)
            
            # Give user a moment to navigate if needed
            await page.wait_for_timeout(2000)
            
            # Extract cookies from browser context
            cookies = await context.cookies()
            
            # Convert to Netscape format for yt-dlp compatibility
            netscape_cookies = convert_cookies_to_netscape(cookies)
            
            # Save cookies to file
            with open(cookies_path, 'w') as f:
                f.write(netscape_cookies)
            
            await browser.close()
            
            return {
                'success': True,
                'message': 'YouTube authentication successful! You can now download age-restricted and region-locked videos.'
            }
            
        except Exception as e:
            await browser.close()
            return {
                'success': False,
                'message': f'Authentication error: {str(e)}'
            }

def convert_cookies_to_netscape(cookies):
    """Convert Playwright cookies to Netscape format for yt-dlp.
    
    Netscape format:
    .domain  flag  path  secure  expiration  name  value
    """
    lines = [
        '# Netscape HTTP Cookie File',
        '# This file contains cookies for YouTube authentication',
        '# It was automatically generated by Soundboard'
    ]
    
    for cookie in cookies:
        if cookie['name'] in ['VISITOR_INFO1_LIVE', 'PREF', 'YSC', '__Secure-YEC']:
            # Only save important YouTube cookies
            domain = cookie.get('domain', '.youtube.com')
            if not domain.startswith('.'):
                domain = '.' + domain
            
            flag = 'TRUE' if cookie.get('domain') else 'FALSE'
            path = cookie.get('path', '/')
            secure = 'TRUE' if cookie.get('secure', False) else 'FALSE'
            expiration = int(cookie.get('expires', time.time() + 365*24*60*60))
            name = cookie.get('name', '')
            value = cookie.get('value', '')
            
            line = f"{domain}\t{flag}\t{path}\t{secure}\t{expiration}\t{name}\t{value}"
            lines.append(line)
    
    return '\n'.join(lines) + '\n'

def download_yt_audio(url, user_id):
    """Download YouTube audio as mp3.
    
    To avoid "Sign in to confirm you're not a bot" errors:
    1. Export YouTube cookies from your browser using a browser extension
    2. Save them to a file: ~/.config/yt-dlp/cookies.txt
    3. The function will automatically use them if available
    
    Alternatively, the app can work with public/unlisted videos without cookies.
    """
    user_dir = SOUNDS_DIR / str(user_id)
    user_dir.mkdir(exist_ok=True)
    filename = f"{uuid4()}.mp3"
    filepath = user_dir / filename

    # Check for cookies file (supports yt-dlp cookie format)
    cookies_path = get_cookies_path()
    
    ydl_opts = {
        'format': 'bestaudio/best',
        'outtmpl': str(filepath.with_suffix('.%(ext)s')),
        'postprocessors': [{
            'key': 'FFmpegExtractAudio',
            'preferredcodec': 'mp3',
            'preferredquality': '192',
        }],
        'quiet': False,
        'no_warnings': False,
        'socket_timeout': 30,
        'http_headers': {
            'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36',
        },
        'extractor_args': {
            'youtube': {
                'player_client': ['web'],
            }
        },
    }
    
    # Add cookies if they exist
    if cookies_path.exists():
        ydl_opts['cookiefile'] = str(cookies_path)
    
    with YoutubeDL(ydl_opts) as ydl:
        ydl.download([url])
    return str(filepath.relative_to(SOUNDS_DIR))